### ISSUE TITLE
Please don't send end() when abort() is called

### ISSUE THREAD

**Issue by rogierschouten** [poelstra/ts-stream#6] opened 2015-06-15 09:24 UTC
The abort() method rejects any subsequent writes. It also sends end() events to readers, but this is not handy. 

- the writing side has to end the stream anyway, and it keeps code clearer to have just one ending procedure
- the ender callback on the forEach get called in the middle of a write callback now, this can surprise users

**Comment by poelstra** [comment] 2015-06-15 09:40
One idea that also popped up was to have an (optional) third callback to forEach(), that would be called in case of aborts, and allows a lengthy read and/or end callback to be prematurely terminated.

This way, transforms can opt-in to support aborting, but correctness of the program is still maintained if they don't (but aborting might be 'slower' then).

**Comment by poelstra** [comment] 2015-06-15 17:11
Consider the following (contrived) case:
* values A, B, C are written (in one go)
* the reader processed value A, then processes value B, which takes a while
* 'someone' decides to abort the stream at this point
* writer still writes D
* writer already writes end without error

Obviously, write(A) succeeds.
However, what would be the best way to handle the rest?

Some possible cases for handling of failing or still allowing the writes:

1. immediately let write() of B, C and D be rejected with the abort-error, let the reader of B finish, but discard C and D. Advantage: fast indication of abort to write-side, disadvantage: no idea which values may or may not have reached a reader (e.g. B was still processed, although its write indicates failure).
2. wait until B finishes and let its write succeed, then let writes of C and D be rejected. Advantage: clear what values have been processed, and possibility to handle a potential error of the reader, disadvantage: slow(er) response to abort.
3. completely let the processing of B and C be done (resolving its writes after read completed), then start to abort writes that happened after the abort (D, in this case). Advantage: none?, disadvantage: even slower response to abort. 

Then there's the case of handling the stream end. In this case:

1. should the ender be called without an error, and end()'s promise be resolved with ender's result?
2. should the ender be called with the abort reason, and end()'s promise be resolved with ender's result?
3. should the ender be called with the abort reason, and end()'s promise be rejected with abort reason?
4. should we require that an abort always needs to be explicitly 'confirmed' (e.g. such that an error can be passed to the ender)? In this case, the already-written end() would then be failed (because it happened before the abort), and then another end() would be required when there are no pending writes anymore?

Points to consider:
* writes should never resolve in a different order, i.e. don't reject write(D) before the previous writes have been resolved (either fulfilled or rejected)
* if we'd use the third-callback-to-abort idea, the reader could implement a mechanism to prematurely abort its handling of B, so the "wait until B is processed"-part may actually be not that bad in practice
* ending the stream is also a form of writing, so it's a bit strange that that is still allowed (required, even) after abort
* should abort() be present on Readable and/or Writable interface

I think I'm in favor of option 2 for the writing (ensures program correctness, readers can opt-in to make it fast, and readers that don't opt-in will at least not get any more values).

For the ending, here's some pro's and con's to each:

1. Simply passing end()'s argument to the ender ("ok", in this case) might lead to unexpected results. E.g. writing the values of a short array in one burst could then appear at the reader as just a truncated array (given there's no error at the end).
2. Conversely, returning OK from end() may lead to unexpected results from the writer side if the abort() happened after the last write. In that case, the writer will never know the stream was in fact aborted (which may not be a real issue, if the full stream, including its eof was indeed completely processed by the reader)
3. This might be a sensible solution, in that end() is not required after an abort (in fact, it is then basically made an error) so there's no possibility to forget to call it. You'd still want to know when the whole chain of stream elements has completely processed the abort, which might be handled automatically with the help of #7.
4. Seems way to complex to me, and especially because this won't be the good-path, it's going to be forgotten.

I'm leaning in the direction of 3 here.

Basically, the total behavior would then be:
* abort() allows a pending read to finish (but optionally does call forEach()'s third callback, if we implement that), still resolves that write with the value of the reader
* all further (pending and future) write()'s will be rejected with the abort error
* end callback is called with the abort error
* end()'s promise is resolved after end callback has completed, but still with abort error (or maybe just the result of the ender?)
* abort() could return a promise that resolves when the stream has completed its abort
* because it still flows 2 ways (aborting writes, and ending stream), it would remain on both Readable and Writable interfaces

@rogierschouten This will not solve your first bullet (because ending the stream after abort is still going to be an error, like any write), but I think your main reason for that was the wish to properly allow waiting for the stream to end (which is guaranteed if we do wait for ender's result before rejecting end(), and could also be the result of ended()).
It does solve your second bullet.
What do you think?

**Comment by rogierschouten** [comment] 2015-06-15 20:09
Good use case!

I agree with no. 2 writing.

I would go for no. 2 ending, because this is composable whereas no. 3 is not. 
No. 3 requires dropping the sink ender's response and replacing it with abort error. Dropping responses sounds like a corner case waiting to bite someone. 

In practical cases I think the writer typically does not care for the abort in the mentioned case - there's nothing left for him to abort so he doesn't have to be bothered. The reader will know, cause he gets the abort error in the end()

It's up to the source & sink implementer to agree on whether to: 
- return the abort error from the ender in the sink,  and
- move the abort error from a write result to the end() in the source
I would keep that a contract between those two in case they care to always know when an abort has happened.

**Comment by poelstra** [comment] 2015-06-16 07:31
A strange thing with going with 2 (for ending), is that it's possible to call end(), and it will actually usually return "OK", but the value passed to end() will not be passed to the end callback (because the abort has already been passed).

I agree that dropping responses may bite someone, but note that a similar thing happens with Promises, which ignore all but the first resolve (which could be reject).

**Comment by poelstra** [comment] 2015-06-20 22:05
Implemented in 0.5.0.

To recap, `abort()` now:
* waits for pending read callback to finish (i.e. that `write()` isn't immediately aborted)
* all further `write()`s are reject with the abort error
* writer must always call `end()`, but any error passed to it will be ignored
* when `end()` is called, ender callback is called with the abort error
* result of `end()` call is result of ender callback

Reason for ignoring `end()`'s error and always passing the abort error to the ender is to properly handle the case where someone does: `write(1)`, `write(2)`, `end()`, without waiting for each of the individual writes, but an abort is called before all writes are processed. In that case, you still would want the reader to be notified of the abort (i.e. not blindly pass the 'no error' from the already-queued `end()`).

Reason for always requiring manual `end()` is to make code more easy to write (i.e. no need to distinguish between stream abort and other write errors), and to allow write side to clean up resources before signalling end.

Because `abort()` is now basically 'just' signals abort to write-side, and doesn't automatically end the read-side of the stream, the method has been removed from the Writable interface.

Remaining work is to add optional 'aborter' callback to `forEach()`, to allow early termination of long-running reader callbacks. Tracked by #6.

**Closed by poelstra** 2015-06-20 22:05 UTC
